### ISSUE TITLE
Falta import en CategoryIT

### ISSUE THREAD

**Issue by powerfrontier** [ccsw-csd/tutorial#2]
En la sección de "Desarrollo con Springboot > Capa de Testing: TDD > Pruebas de listado"
, en el segundo listado del fichero CategoryIT el eclipse se queja que en la línea 39 no puede reconocer el objeto HttpMethod y me sugiere que haga un import. Haciéndolo (`import org.springframework.http.HttpMethod`) el error se soluciona.

**Comment by pajimene** [comment]
Lo hemos corregido con la migración a Springboot 3.

Muchas gracias :-)
